exports.seed = function(knex) {
  // Deletes ALL existing entries
  return knex("users")
    .del()
    .then(function() {
      // Inserts seed entries
      return knex("users").insert([
        {
          id: 1,
          name: "Don",
          email: "don@email.com",
          mobile: 1234567,
          password: "yoda",
          balance: 3,
          address: "12 Morgan Street, Newmarket, 0600",
          latitude: -36.8645,
          longitude: 174.77673,
          image: "/images/avatar01.png"
        },
        {
          id: 2,
          name: "Bryce",
          email: "bryce@email.com",
          mobile: 1111111,
          password: "hansolo",
          balance: 3,
          address: "1 George Street, Newmarket, 0600",
          latitude: -36.8644,
          longitude: 174.77502,
          image: "/images/avatar01.png"
        },
        {
          id: 3,
          name: "Emily",
          email: "emily@email.com",
          mobile: 2222222,
          password: "amidala",
          balance: 3,
          address: "98 Carlton Gore Road, Newmarket, 0600",
          latitude: -36.8649,
          longitude: 174.77572,
          image: "/images/avatar01.png"
        },
        {
          id: 4,
          name: "Jess",
          email: "jess@email.com",
          mobile: 3333333,
          password: "padme",
          balance: 3,
          address: "424 Khyber Pass Road, Newmarket, 0600",
          latitude: -36.86723,
          longitude: 174.77686,
          image: "/images/avatar01.png"
        },
        {
          id: 5,
          name: "Piha",
          email: "piha@email.com",
          mobile: 4444444,
          password: "firstorder",
          balance: 3,
          address: "12 Morgan Street, Newmarket, 0600",
          latitude: -36.8645,
          longitude: 174.77673,
          image: "/images/avatar01.png"
        },
        {
          id: 6,
          name: "Andria",
          email: "andria@email.com",
          mobile: 5555555,
          password: "dagobah",
          balance: 3,
          address: "1 George Street, Newmarket, 0600",
          latitude: -36.8644,
          longitude: 174.77502,
          image: "/images/avatar01.png"
        },
        {
          id: 7,
          name: "Jeya",
          email: "jeya@email.com",
          mobile: 6666666,
          password: "poedameron",
          balance: 3,
          address: "98 Carlton Gore Road, Newmarket, 0600",
          latitude: -36.8649,
          longitude: 174.77572,
          image: "/images/avatar01.png"
        },
        {
          id: 8,
          name: "Marina",
          email: "marina@email.com",
          mobile: 7777777,
          password: "bb8",
          balance: 3,
          address: "424 Khyber Pass Road, Newmarket, 0600",
          latitude: -36.86723,
          longitude: 174.77686,
          image: "/images/avatar01.png"
        },
        {
          id: 9,
          name: "Sam",
          email: "sam@email.com",
          mobile: 8888888,
          password: "ackbar",
          balance: 3,
          address: "12 Morgan Street, Newmarket, 0600",
          latitude: -36.8645,
          longitude: 174.77673,
          image: "/images/avatar01.png"
        },
        {
          id: 10,
          name: "Suzana",
          email: "suzana@email.com",
          mobile: 99999999,
          password: "leia",
          balance: 3,
          address: "1 George Street, Newmarket, 0600",
          latitude: -36.8644,
          longitude: 174.77502,
          image: "/images/avatar01.png"
        },
        {
          id: 11,
          name: "Jill",
          email: "jill@email.com",
          mobile: 1010101,
          password: "rey",
          balance: 3,
          address: "98 Carlton Gore Road, Newmarket, 0600",
          latitude: -36.8649,
          longitude: 174.77572,
          image: "/images/avatar01.png"
        },
        {
          id: 12,
          name: "Roman",
          email: "roman@email.com",
          mobile: 1212121,
          password: "kylo",
          balance: 3,
          address: "424 Khyber Pass Road, Newmarket, 0600",
          latitude: -36.86723,
          longitude: 174.77686,
          image: "/images/avatar01.png"
        },
        {
          id: 13,
          name: "Adam",
          email: "adam@email.com",
          mobile: 1313131,
          password: "alderaan",
          balance: 3,
          address: "12 Morgan Street, Newmarket, 0600",
          latitude: -36.8645,
          longitude: 174.77673,
          image: "/images/avatar01.png"
        },
        {
          id: 14,
          name: "Ash",
          email: "ash@email.com",
          mobile: 1414141,
          password: "chewbacca",
          balance: 3,
          address: "1 George Street, Newmarket, 0600",
          latitude: -36.8644,
          longitude: 174.77502,
          image: "/images/avatar01.png"
        },
        {
          id: 15,
          name: "Elly",
          email: "elly@email.com",
          mobile: 1515151,
          password: "jabba",
          balance: 3,
          address: "98 Carlton Gore Road, Newmarket, 0600",
          latitude: -36.8649,
          longitude: 174.77572,
          image: "/images/avatar01.png"
        },
        {
          id: 16,
          name: "Jackie",
          email: "jackie@email.com",
          mobile: 1616161,
          password: "lando",
          balance: 3,
          address: "424 Khyber Pass Road, Newmarket, 0600",
          latitude: -36.86723,
          longitude: 174.77686,
          image: "/images/avatar01.png"
        },
        {
          id: 17,
          name: "Peter",
          email: "peter@email.com",
          mobile: 1717171,
          password: "bobafett",
          balance: 3,
          address: "12 Morgan Street, Newmarket, 0600",
          latitude: -36.8645,
          longitude: 174.77673,
          image: "/images/avatar01.png"
        },
        {
          id: 18,
          name: "Sunny",
          email: "sunny@email.com",
          mobile: 1818181,
          password: "endor",
          balance: 3,
          address: "1 George Street, Newmarket, 0600",
          latitude: -36.8644,
          longitude: 174.77502,
          image: "/images/avatar01.png"
        },
        {
          id: 19,
          name: "Carolyn",
          email: "carolyn@email.com",
          mobile: 1919191,
          password: "obiwan",
          balance: 3,
          address: "98 Carlton Gore Road, Newmarket, 0600",
          latitude: -36.8649,
          longitude: 174.77572,
          image: "/images/avatar01.png"
        },
        {
          id: 20,
          name: "Doug",
          email: "doug@email.com",
          mobile: 2020202,
          password: "tatooine",
          balance: 3,
          address: "424 Khyber Pass Road, Newmarket, 0600",
          latitude: -36.86723,
          longitude: 174.77686,
          image: "/images/avatar01.png"
        },
        {
          id: 21,
          name: "Anita",
          email: "Anita@email.com",
          mobile: 2121212,
          password: "c3po",
          balance: 3,
          address: "12 Morgan Street, Newmarket, 0600",
          latitude: -36.8645,
          longitude: 174.77673,
          image: "/images/avatar01.png"
        },
        {
          id: 22,
          name: "Ham",
          email: "ham@email.com",
          mobile: 0202020,
          password: "r2d2",
          balance: 3,
          address: "1 George Street, Newmarket, 0600",
          latitude: -36.8644,
          longitude: 174.77502,
          image: "/images/avatar01.png"
        },
        {
          id: 23,
          name: "Sarah",
          email: "sarah@email.com",
          mobile: 2323232,
          password: "leia",
          balance: 3,
          address: "98 Carlton Gore Road, Newmarket, 0600",
          latitude: -36.8649,
          longitude: 174.77572,
          image: "/images/avatar01.png"
        },
        {
          id: 24,
          name: "Phoenix",
          email: "phoenix@email.com",
          mobile: 2424242,
          password: "luke",
          balance: 3,
          address: "424 Khyber Pass Road, Newmarket, 0600",
          latitude: -36.86723,
          longitude: 174.77686,
          image: "/images/avatar01.png"
        },
        {
          id: 25,
          name: "Kristie",
          email: "kristie@email.com",
          mobile: 2525252,
          password: "vader",
          balance: 3,
          address: "12 Morgan Street, Newmarket, 0600",
          latitude: -36.8645,
          longitude: 174.77673,
          image: "/images/avatar01.png"
        },
        {
          id: 26,
          name: "Joshua",
          email: "joshua@email.com",
          mobile: 2626262,
          password: "naboo",
          balance: 3,
          address: "1 George Street, Newmarket, 0600",
          latitude: -36.8644,
          longitude: 174.77502,
          image: "/images/avatar01.png"
        }
      ]);
    });
};
